{
	"version": 1733068755,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/smkn1banyuwangi-sheet0.png",
		"images/rpl-sheet0.png",
		"images/merah-sheet0.png",
		"images/hijau-sheet0.png",
		"images/biru-sheet0.png",
		"images/kitchenbg.png",
		"images/kitchenobs.png",
		"images/gelasmerah.png",
		"images/level1bg-sheet0.png",
		"images/glass-sheet0.png",
		"images/background-sheet0.png",
		"images/pesanbg-sheet0.png",
		"images/witch-sheet0.png",
		"images/witch-sheet1.png",
		"images/witch-sheet2.png",
		"images/messagebg-sheet0.png",
		"media/collect coin.ogg",
		"media/start menu.ogg",
		"media/level1.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}